### ISSUE TITLE
Cannot find textures if TerraUI in base directory

### ISSUE THREAD

**Issue by gamrguy** [TerraUI/TerraUI#1]
If TerraUI is placed in the mod's base directory, the mod will be unable to get the textures from the Textures folder. This is because of a stray `/` in front of the default directories.

Fix: Remove the stray `/`. Mods which use a special directory to store TerraUI can add the `/` themselves when setting Subdirectory in UIUtils.

(Also, hi, I'm thegamemaster1234 from the Terraria forums! I've been trying to use this newer version for a GUI, but can't seem to find the proper place to put the Update call. Help please?

...and I heard from Boffin that this isn't finished, so if some things just don't work yet, that's OK)

**Comment by abluescarab** [comment]
Gamemaster, 

Thanks for letting us know! We're still hard at work adding new features and fixing old ones. It's always helpful when someone comes along to tell us about a bug. I'm just about to go to bed, but if Boffin doesn't get to it before I do, I'll fix it as soon as I get up. Apologies for the late reply! 

As a side note, the folder structure of TerraUI is still changing. You might find that having the toolkit in a subdirectory will keep your project cleaner. :) 

I also realized after I woke up that I forgot to address your Update() question. I would recommend putting it in a ModPlayer's PreUpdate() function. Check out our [example ModPlayer](https://github.com/TerraUI/TerraUI/blob/testmod/TerraUITestPlayer.cs) to see what we did.

I'll close this issue when the bug no longer occurs.

**Comment by abluescarab** [comment]
I also realized after I woke up that I forgot to address your Update() question. I would recommend putting it in a ModPlayer's PreUpdate() function. Check out our [example ModPlayer](https://github.com/TerraUI/TerraUI/blob/testmod/TerraUITestPlayer.cs) to see what we did.

**Comment by abluescarab** [comment]
The eabd90b1ad667956fc3dd20bde63846286820567 commit should solve this issue. I tested it and it seemed to work fine.

Check out the wiki entry on [UIUtils.GetTexture()](https://github.com/TerraUI/TerraUI/wiki/UIUtils#gettexture) and let me know if this solves your issue.

**Comment by gamrguy** [comment]
The fix in that commit will fix the issue, although I do feel that it is a slight bit overboard (do you really have to error-check the person using the framework? Is it that hard to have users include a trailing / ? ...but I digress).

I find it quite interesting that GUI handling is now being performed from within a ModPlayer class as opposed to a standalone class.

Also, thanks for the suggestions, I'll be sure to consider them!

**Comment by abluescarab** [comment]
I didn't write the helper function to error-check the user, but rather to make it easier on them. They can format the subdirectory a few ways, and it will still work correctly.

Boffin also found that the UI works better in multiplayer if the update events are placed in a ModPlayer class. We intend to update the toolkit to make the keyboard and mouse events non-static so they work for all players.
